### ISSUE TITLE
Break into parts

### ISSUE THREAD

**Issue by friendly** [friendly/Vis-MLM-book#16]
I'd like to break the chapters into parts, as indicated in `working-text/Parts.txt`, but I ran into problems.

```
Preface

Part I: Orienting Ideas
1  Introduction
2  Getting Started

Part II: Exploratory Methods
3  Plots of Multivariate Data
4  Dimension Reduction

Part III: Univariate Linear Models
5  Overview of Linear models
6  Plots for univariate response models
7  Topics in Linear Models
8  Collinearity & Ridge Regression

Part IV: Multivariate Linear Models
9  Hotelling's
10  Multivariate Linear Models
11  Visualizing Multivariate Models
12  Visualizing Equality of Covariance Matrices
13  Case studies

References
Colophon
Appendices (??)
```

In `_quarto.yml` I tried this. For now, just a part page with the part title, but ultimately I'd like to include an image or text, so there would be part files like `I-orienting.qmd`, ...

```
  chapters:
    - index.qmd
    - part: "Orienting Ideas"
    chapters:
      - 01-intro.qmd
      - 02-getting_started.qmd
    - part: "Exploratory Methods"
    chapters:
      - 03-multivariate_plots.qmd
      - 04-pca-biplot.qmd
    - part: "Univariate Linear Models"
    chapters:
      - 05-linear_models.qmd
      - 06-linear_models-plots.qmd
      - 07-lin-mod-topics.qmd
      - 08-collinearity-ridge.qmd
      - part: "Multivariate Linear Models"
    chapters:
      - 09-hotelling.qmd
      - 10-mlm-review.qmd
      - 11-mlm-viz.qmd
      - eqcov.qmd
      - case-studies.qmd
    # - summary.qmd
    # these should not be in a Part
  - 90-references.qmd
  - 91-colophon.qmd
  appendices:
```

But I got the error below:

```
ERROR: YAMLException: bad indentation of a mapping entry (C:\R\projects\Vis-MLM-book\_quarto.yml, 72:5)
71:     - part: "Orienting Ideas"
72:     chapters:
       ~~
73:       - 01-intro.qmd
```

**Comment by cscheid** [comment]
This one is a YAML annoyance, but it's an easy fix! The `chapters` field needs to be indented consistent with the `part` field.  Instead of:

````
  chapters:
    - index.qmd
    - part: "Orienting Ideas"
    chapters:
      - 01-intro.qmd
      - 02-getting_started.qmd
...
````

try

````
  chapters:
    - index.qmd
    - part: "Orienting Ideas"
      chapters:
        - 01-intro.qmd
        - 02-getting_started.qmd
````

**Comment by friendly** [comment]
Great. thanks.  But what about the end, with the References, Colophon and possible Appendices.  I had to comment out `appendices` to get this to work.

```
  chapters:
    - index.qmd
    - part: "Orienting Ideas"
      chapters:
        - 01-intro.qmd
        - 02-getting_started.qmd
    - part: "Exploratory Methods"
      chapters:
        - 03-multivariate_plots.qmd
        - 04-pca-biplot.qmd
    - part: "Univariate Linear Models"
      chapters:
        - 05-linear_models.qmd
        - 06-linear_models-plots.qmd
        - 07-lin-mod-topics.qmd
        - 08-collinearity-ridge.qmd
    - part: "Multivariate Linear Models"
      chapters:
        - 09-hotelling.qmd
        - 10-mlm-review.qmd
        - 11-mlm-viz.qmd
        - eqcov.qmd
        - case-studies.qmd
    # - summary.qmd
    # these should not be in a Part
        - 90-references.qmd
        - 91-colophon.qmd
    # appendices:
```
